'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Reflection
<Assembly: System.Reflection.AssemblyCompanyAttribute("Library_System_New"),  _
 Assembly: System.Reflection.AssemblyConfigurationAttribute("Debug"),  _
 Assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0"),  _
 Assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+8c185e5f349fea0d2b41e4262762f73c7313efe2"),  _
 Assembly: System.Reflection.AssemblyProductAttribute("Library_System_New"),  _
 Assembly: System.Reflection.AssemblyTitleAttribute("Library_System_New"),  _
 Assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0"),  _
 Assembly: System.Runtime.Versioning.TargetPlatformAttribute("Windows7.0"),  _
 Assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Windows7.0")> 

'Generated by the MSBuild WriteCodeFragment class.
